# Generated by Django 5.0 on 2026-01-15 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despesas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastro'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriadespesa',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['empresa', 'data_vencimento'], name='despesas_de_empresa_0fe528_idx'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['empresa', 'status'], name='despesas_de_empresa_ae5ad9_idx'),
        ),
    ]
