# Generated by Django 5.0 on 2026-01-15 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receitas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='usuario_cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Cadastro'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriareceita',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['empresa', 'data_prevista'], name='receitas_re_empresa_f42cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['empresa', 'status'], name='receitas_re_empresa_ade08c_idx'),
        ),
    ]
