# Generated by Django 5.0 on 2026-01-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '__first__'),
        ('receitas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='categorias.categoria', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='CategoriaReceita',
        ),
    ]
