# Generated by Django 5.0 on 2026-01-17 22:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='chargeback',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de estorno/contestacao', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Chargeback'),
        ),
        migrations.AddField(
            model_name='venda',
            name='reversao_chargeback',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de chargeback recuperado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Reversao de Chargeback'),
        ),
    ]
